---
services:
  minio:
    image: quay.io/minio/minio:RELEASE.2025-02-07T23-21-09Z
    container_name: minio
    hostname: minio
    restart: always
    shm_size: 128mb
    ports:
      - "9000:9000"
      - "9001:9001"
    env_file:
      - ./env/minio.env
      - ./env/minio.secrets.env
    volumes:
      - minio_data:/data
    networks:
      - minio_net
    command:
      - server
      - /data
      - --console-address
      - ":9001"
    healthcheck:
      test: [ "CMD", "curl", "--fail", "http://127.0.0.1:9000/minio/health/live" ]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 60s


volumes:
  minio_data:
    name: minio-data


networks:
  minio_net:
    name: minio-network