---
services:
  postgresql:
    image: postgres:17-alpine
    container_name: postgres
    hostname: postgres
    restart: always
    shm_size: 128mb
    ports:
      - "5432:5432"
    env_file:
      - ./env/postgres.env
      - ./env/postgres.secrets.env
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - pg_net
    command:
      - postgres
      - -c
      - wal_level=logical
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s


volumes:
  pg_data:
    name: postgres-data


networks:
  pg_net:
    name: postgres-network